### ISSUE TITLE
Potential bug  chk_dsclate (EMR discharge before) and chk_dscearly (emr discharge after) 

### ISSUE THREAD

**Issue by Milanara** [bokov/nsqip_emr#6]
You probably already checked these, but chk_dsclate (EMR discharge before) and chk_dscearly (emr discharge after) are the exact same number so I'd be a bad reviewer if I didn't mention that and advise double checking the code to make sure there isn't a bug causing them to both be the same thing.

**Comment by bokov** [comment]
Thanks. Backwards > sign, now fixed. In the updated version the counts are different, have a look.
